# Generated by Django 3.0.3 on 2025-06-05 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bedrooms', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('posted_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'apartments',
                'ordering': ['-posted_date'],
            },
        ),
    ]
